[package]
name = "spark-rust-sdk-examples"
version = "0.1.0"
edition = "2021"
authors = ["alexey <alexnagornnyy.an@gmail.com>", "partylikeits1983 <aleqvids@gmail.com>"]
license = "Apache-2.0"

[dependencies]
fuels = { version = "0.65.1", features = ["fuel-core-lib"] }
tokio = { version = "1.12", features = ["rt", "macros"] }
spark-market-sdk = { git = "https://github.com/compolabs/orderbook-contract.git", branch = "sdk-tests" }
src20_sdk = { git = "https://github.com/compolabs/src-20.git", branch = "testnet" }
anyhow = "1.0.86"
dotenv = "0.15.0"
serde = "1.0.204"